plugins {
    id 'java'
    id "me.champeau.jmh" version "0.7.0"
}

group = 'ru.tbank'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation platform('org.junit:junit-bom:5.10.0')

    implementation 'org.openjdk.jmh:jmh-core:1.37'
    testImplementation 'org.openjdk.jmh:jmh-core:1.37'
    annotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    testImplementation 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    implementation 'org.apache.kafka:kafka-clients:3.9.0'
    implementation 'com.rabbitmq:amqp-client:5.23.0'

    implementation 'org.slf4j:slf4j-api:2.0.16'
    testImplementation 'org.slf4j:slf4j-simple:2.0.16'
}

jmh { // 1 повтор бенчмарка, 1 прогревочная итерация, 3 итераций
    fork = 1
    warmupIterations = 1
    iterations = 3
}

sourceSets {
    jmh {
        java.srcDirs = ['src/main/java']
        compileClasspath += sourceSets.main.runtimeClasspath
    }
}

test {
    useJUnitPlatform()
}